// Generated by scripts/build-ecad-viewer.sh. Do not edit by hand.
//
// The renderer is a public asset rather than a Vite-processed module, so it
// carries its own cache key. The digest is the artifact's, matching the
// manifest, so a changed bundle always gets a new browser identity.
export const ECAD_RENDERER_URL = "/ecad-renderer.js?v=9ec9e4741ea475636918cad95bd6e8427aa32ccf6a0f1df44efe5d9802bf9be8";
